spring:
  datasource:
    url:
      username: User_For_DB
      password: 1999
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialec.PostgreSQLDialect
